import { PrismaClient } from '@prisma/client';
import { pecbCatalogue } from './pecb-catalogue.js';

const prisma = new PrismaClient();

const courses = [
    { slug: 'iso-iec-27001-foundation', title: 'ISO/IEC 27001', subtitle: 'Foundation', track: 'Cybersecurity', level: 'Foundation', deliveryMode: 'Self-paced', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Build practical competence across the fundamentals of information security management.', sortOrder: 1 },
    { slug: 'iso-iec-27001-lead-implementer', title: 'ISO/IEC 27001', subtitle: 'Lead Implementer (PECB Certified)', track: 'Cybersecurity', level: 'Advanced', deliveryMode: 'Hybrid', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Advance into implementation planning and operational delivery for ISO/IEC 27001 information security management systems.', sortOrder: 2 },
    { slug: 'iso-iec-27001-lead-auditor', title: 'ISO/IEC 27001', subtitle: 'Lead Auditor (PECB Certified)', track: 'Cybersecurity', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Develop the knowledge to audit and assess information security management systems.', sortOrder: 3 },
    { slug: 'cybersecurity-fundamentals', title: 'Cybersecurity', subtitle: 'Fundamentals', track: 'Cybersecurity', level: 'Foundation', deliveryMode: 'Self-paced', overview: 'A practical introduction to an evolving security landscape and threat awareness.', sortOrder: 4 },
    { slug: 'enterprise-risk-management', title: 'Enterprise Risk', subtitle: 'Management', track: 'GRC', level: 'Professional', deliveryMode: 'Virtual', overview: 'Apply structured approaches to enterprise risk identification and management.', sortOrder: 5 },
    { slug: 'iso-31000-risk-management', title: 'ISO 31000', subtitle: 'Risk Management', track: 'GRC', level: 'Professional', deliveryMode: 'Hybrid', overview: 'Develop confidence in governance and risk management using ISO 31000 principles.', sortOrder: 6 },
    { slug: 'compliance-regulatory-governance', title: 'Compliance & Regulatory', subtitle: 'Governance', track: 'GRC', level: 'Professional', deliveryMode: 'Virtual', overview: 'Connect governance, compliance, and regulatory priorities into practical action.', sortOrder: 7 },
    { slug: 'ai-governance-fundamentals', title: 'AI Governance', subtitle: 'Fundamentals', track: 'AI Governance', level: 'Foundation', deliveryMode: 'Self-paced', overview: 'Understand the ethical, legal, and governance dimensions of AI adoption.', sortOrder: 8 },
    { slug: 'responsible-ai-leadership', title: 'Responsible AI', subtitle: 'Leadership', track: 'AI Governance', level: 'Executive', deliveryMode: 'Virtual', overview: 'Prepare leaders to guide responsible AI adoption across the organization.', sortOrder: 9 },
    { slug: 'ai-risk-management', title: 'AI Risk', subtitle: 'Management', track: 'AI Governance', level: 'Professional', deliveryMode: 'Hybrid', overview: 'Translate AI risks into practical governance and control frameworks.', sortOrder: 10 },
    { slug: 'iso-iec-42001-ai-management-systems', title: 'ISO/IEC 42001', subtitle: 'AI Management Systems (PECB Certified)', track: 'AI Governance', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Develop capability in implementing AI Management Systems aligned to emerging standards.', sortOrder: 11 },
    { slug: 'cybersecurity-for-executives', title: 'Cybersecurity', subtitle: 'for Executives', track: 'Executive Leadership', level: 'Executive', deliveryMode: 'In-person', overview: 'Equip executives to understand cyber risk and lead with confidence.', sortOrder: 12 },
    { slug: 'digital-risk-for-board-leaders', title: 'Digital Risk', subtitle: 'for Board Leaders', track: 'Executive Leadership', level: 'Executive', deliveryMode: 'In-person', overview: 'Support boards in navigating digital risk and governance obligations.', sortOrder: 13 },
    { slug: 'technology-governance-leadership', title: 'Technology Governance', subtitle: '& Leadership', track: 'Executive Leadership', level: 'Executive', deliveryMode: 'Hybrid', overview: 'Build executive capability around technology governance and leadership decision-making.', sortOrder: 14 },
    { slug: 'iso-22301-lead-implementer', title: 'ISO 22301', subtitle: 'Lead Implementer (PECB Certified)', track: 'GRC', level: 'Advanced', deliveryMode: 'Hybrid', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Design, implement and manage a business continuity management system aligned to ISO 22301.', sortOrder: 15 },
    { slug: 'iso-22301-lead-auditor', title: 'ISO 22301', subtitle: 'Lead Auditor (PECB Certified)', track: 'GRC', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Audit business continuity management systems with authority and precision.', sortOrder: 16 },
    { slug: 'iso-27005-lead-risk-manager', title: 'ISO/IEC 27005', subtitle: 'Lead Risk Manager (PECB Certified)', track: 'Cybersecurity', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Master information security risk management end to end: context, assessment, treatment and monitoring.', sortOrder: 17 },
    { slug: 'iso-27035-lead-incident-manager', title: 'ISO/IEC 27035', subtitle: 'Lead Incident Manager (PECB Certified)', track: 'Cybersecurity', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Lead detection, response and recovery from information security incidents.', sortOrder: 18 },
    { slug: 'iso-27032-lead-cybersecurity-manager', title: 'ISO/IEC 27032', subtitle: 'Lead Cybersecurity Manager (PECB Certified)', track: 'Cybersecurity', level: 'Advanced', deliveryMode: 'Hybrid', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Lead organization-wide cybersecurity programmes, stakeholder collaboration and resilience controls.', sortOrder: 19 },
    { slug: 'iso-37301-compliance-lead-implementer', title: 'ISO 37301', subtitle: 'Compliance Management — Lead Implementer (PECB Certified)', track: 'GRC', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Establish and operate a compliance management system with integrity.', sortOrder: 20 },
    { slug: 'iso-37001-anti-bribery-lead-implementer', title: 'ISO 37001', subtitle: 'Anti-bribery — Lead Implementer (PECB Certified)', track: 'GRC', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Build anti-bribery management systems that protect reputation and meet global expectations.', sortOrder: 21 },
    { slug: 'iso-27005-risk-manager', title: 'ISO/IEC 27005', subtitle: 'Risk Manager (PECB Certified)', track: 'Cybersecurity', level: 'Professional', deliveryMode: 'Self-paced', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Practitioner-level information security risk management using ISO/IEC 27005.', sortOrder: 22 },
    { slug: 'iso-iec-20000-lead-implementer', title: 'ISO/IEC 20000', subtitle: 'Service Management — Lead Implementer (PECB Certified)', track: 'GRC', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Implement and manage IT service management systems aligned to ISO/IEC 20000.', sortOrder: 23 },
    { slug: 'iso-29100-privacy-framework-lead-implementer', title: 'ISO/IEC 29100', subtitle: 'Privacy Framework — Lead Implementer (PECB Certified)', track: 'Cybersecurity', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Operationalize privacy principles and PII protection across programmes and systems.', sortOrder: 24 },
    { slug: 'iso-27701-pims-lead-implementer', title: 'ISO/IEC 27701', subtitle: 'PIMS — Lead Implementer (PECB Certified)', track: 'Cybersecurity', level: 'Advanced', deliveryMode: 'Virtual', overview: 'A PECB Certified course delivered by Ykay Consulting Hub. Extend ISMS into a privacy information management system for PII controllers and processors.', sortOrder: 25 },
];

const content = [
    { pageKey: 'About', content: { kicker: 'ABOUT YKAY CONSULT', title: 'Purpose-led. Practice-focused. Africa-ready.', description: 'We help professionals and organizations lead with confidence in a world defined by technology and risk.', blocks: [{ title: 'Who We Are', text: 'The Centre for Digital Risk & Leadership is a professional education, certification, and advisory institution focused on cybersecurity, digital governance, AI risk, and leadership development.' }, { title: 'Our Mission', text: 'To equip professionals and organizations with the knowledge, frameworks, and leadership required to manage digital risks in an evolving technological landscape.' }, { title: 'Our Vision', text: 'To become a leading African hub for digital risk education, cybersecurity leadership, and governance excellence.' }, { title: 'Our Core Values', text: 'The principles that shape every learning and advisory engagement.', items: ['Integrity', 'Excellence', 'Innovation', 'Professional Leadership', 'Digital Trust'] }] } },
    { pageKey: 'Corporate Training', content: { kicker: 'CORPORATE TRAINING', title: 'Turn digital risk awareness into organizational resilience.', description: 'Tailored learning experiences for teams, executives, and boards.', blocks: [{ title: 'Why Corporate Training Matters', text: 'Cyber attacks, insider threats, and regulatory risk now affect every function. Your people are your first line of resilience.', items: ['Cyber attacks', 'Insider threats', 'Regulatory exposure'] }, { title: 'Our Services', text: 'Programs are adapted to your sector, workforce, and risk maturity.', items: ['Cybersecurity Awareness Training', 'Executive Cyber Risk Briefings', 'Digital Risk Assessments', 'Governance Workshops'] }] } },
    { pageKey: 'Advisory', content: { kicker: 'ADVISORY & CONSULTING', title: 'Practical guidance for stronger digital governance.', description: 'Translate standards and risk priorities into systems your organization can operate and sustain.', blocks: [{ title: 'Professional Services', text: 'Our advisory work combines internationally recognized frameworks with local operational context.', items: ['ISO 27001 Implementation', 'Cybersecurity Risk Assessment', 'Information Security Audits', 'Digital Governance Advisory', 'Business Continuity Planning'] }] } },
    { pageKey: 'Research', content: { kicker: 'RESEARCH & INSIGHTS', title: 'Clear thinking for complex digital questions.', description: 'Analysis and practical commentary for decision-makers across Africa.', blocks: [{ title: 'The Future of AI Governance in Africa', text: 'How leaders can build responsible, locally relevant governance for rapidly advancing AI systems.' }, { title: 'Why Cybersecurity Leadership Matters', text: 'Cybersecurity is no longer a technical issue—it is an enterprise leadership mandate.' }, { title: 'Understanding ISO 27001 for Organizations', text: 'A practical introduction to building a systematic approach to information security.' }] } },
    { pageKey: 'Events', content: { kicker: 'EVENTS & MASTERCLASSES', title: 'Learn live. Lead with confidence.', description: 'Join upcoming certification programs, briefings, and practitioner masterclasses.', blocks: [{ title: 'ISO/IEC 27001 Lead Implementer', text: 'June 18–21, 2026 · Lagos / Virtual', items: ['Four-day intensive program', 'Official course materials', 'Certification exam preparation'] }, { title: 'Cyber Risk Leadership Masterclass', text: 'August 2026 · Virtual', items: ['For senior leaders and board members', 'Executive briefing format'] }] } },
    { pageKey: 'Partnerships', content: { kicker: 'PARTNERSHIPS', title: 'Stronger ecosystems build greater digital trust.', description: 'We collaborate with institutions that share our commitment to capability, standards, and responsible innovation.', blocks: [{ title: 'Certification Bodies', text: 'Collaborating to deliver credible, internationally aligned professional certifications.' }, { title: 'Universities', text: 'Bridging academic knowledge with practical digital risk and leadership capabilities.' }, { title: 'Corporate Partners', text: 'Co-creating workforce development programs that meet industry needs.' }] } },
    { pageKey: 'Leadership', content: { title: 'Experience that turns knowledge into action.', description: 'Meet the practitioner behind YKAY Consult\'s mission.' } },
    { pageKey: 'Contact', content: { title: 'Let\'s build digital trust together.', description: 'Tell us how YKAY Consult can support your professional or organizational goals.' } },
];

async function main() {
    for (const course of [...courses, ...pecbCatalogue]) {
        await prisma.course.upsert({
            where: { slug: course.slug },
            update: course,
            create: course,
        });
    }

    for (const item of content) {
        await prisma.siteContent.upsert({
            where: { pageKey: item.pageKey },
            update: { content: item.content },
            create: { pageKey: item.pageKey, content: item.content },
        });
    }

    console.log('Seeded CDRL data');
}

main().finally(async () => {
    await prisma.$disconnect();
});
